apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: default  # Specify the namespace here
  annotations:
        prometheus.io/scrape: "true"
        # prometheus.io/path: "/http-metrics"  # Uncomment if metrics are exposed on a specific path
        prometheus.io/port: "80"
spec:
  replicas: 1  # Use multiple replicas to test load balancing
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: miranafea/simple-flask:v1
        ports:
        - containerPort: 80
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name  # Gets the pod name dynamically
