apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
  - host: test.com
    http:
      paths:
      - path: /test
        pathType: Prefix
        backend:
          service:
            name: flask-service
            port:
              number: 5000
      - path: /metrics
        pathType: Prefix
        backend:
          service:
            name: flask-service
            port:
              number: 5000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
