apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  
spec:
  replicas: 3  # Use multiple replicas to test load balancing
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: flask
        image: miranafea/simple-flask-app
        ports:
        - containerPort: 80
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name  # Gets the pod name dynamically
